### ISSUE TITLE
Only run travis builds for node versions 4, 6 and 7

### ISSUE THREAD

**Issue by jedireza** [neon-bindings/neon#149]
Currently we're running builds for rust `stable`, `beta`, `nightly` and node `4.2`, `5.11`, `5`, `6` (which becomes 12 jobs on travis).

I suggest that we change the node versions to `4`, `6`, `7`. By only specifying the major version (ex: `6` not `6.9`) travis will install the latest stable sub-version of the major specified (ex: `6.9.2` for `6`).

I also suggest we only run builds for the supported versions of node and current. Based on the [LTS schedule](https://github.com/nodejs/LTS#lts-schedule), this is `4`, `6`, `7`.

This would also speed-up the build times a bit since it would result in 9 jobs instead of the 12 we have now.

**Comment by dherman** [comment]
So as I understand it, the odd-numbered versions of Node are unstable and get superseded by the even-numbered versions, which turn into LTS. So that's why we (in theory) could drop support for version 5, since 6 is supposed to be compatible with 5 and it should (again, in theory) always be safe for someone to upgrade from 5 to 6, right?

I agree that if Node itself isn't supporting versions earlier than the last LTS, it seems unrealistic for us to try to support them, so only going as far back as the most recent LTS seems wise.

At any rate, until we have more customers, we don't know for sure what people will need, so we have to start somewhere. Keeping our CI reasonably efficient seems like a good goal for now, but we should be willing to revisit if we end up with customers who raise concerns we hadn't thought of.

**Comment by bnoordhuis** [comment]
> since 6 is supposed to be compatible with 5 and it should (again, in theory) always be safe for someone to upgrade from 5 to 6, right?

No.  Node follows semver, a major version bump means there are backwards incompatible changes.

I'd stick with supported versions: currently 4, 6 and 7.

**Comment by dherman** [comment]
@bnoordhuis If it's incompatible to bump from 5 to 6, doesn't that mean we should expect a fair amount of customers not to move right away? I think the open question for me is whether to continue to support the odd-numbered versions or not.

**Comment by dherman** [comment]
@jedireza Here's what I propose as resolution:
- We go with your proposed policy for now, to cut back on build times and maintenance burden.
- We publish our support matrix somewhere clearly. The README is fine if it's not overwhelming but I suspect it'll want a dedicated documentation page.
- If we find more customers over time are using odd-numbered nodes and unable to migrate immediately to even-numbered nodes when they come out, we should be willing to revisit this policy.

**Comment by jedireza** [comment]
@dherman I also noticed we're specifically testing rust `nightly-2016-04-29`. Is there something special about that release or something legacy we can remove while we're at it?

**Comment by dherman** [comment]
@jedireza according to `git blame` it showed up in 58d41e62e54f267dd0d9bf16338b5e7340fc7ec1. I don't recall what was special about that nightly but I highly doubt it's important anymore. Let's just remove it.

@mfpiccolo do you know what the story was behind that specific nightly?
