### ISSUE TITLE
declare_types `for X` should accept path (including ident)

### ISSUE THREAD

**Issue by phrohdoh** [neon-bindings/neon#167]
Currently the following isn't possible:

```rust
declare_types! {
    pub class JsBigArchive for ::BigArchive {
        init(call) {
            let scope = call.scope;
            let path = call.args.require(call.scope, 0)?.check::<JsString>()?.value();
            Ok(::BigArchive::new_from_path(&path)?)
        }
    }
}

/*
error: expected ident, found ::
  --> src/feature_neon/mod.rs:26:32
   |
26 |     pub class JsBigArchive for ::BigArchive {
   |                                ^^

error: Could not compile `libbig`.
*/
```

**Comment by dherman** [comment]
Yeah, this is an annoying papercut! Thanks for the report. I see in #168 you figured out the workaround but we should definitely make it nicer.

I'm not sure if allowing `ty` instead of `ident` will cause grammar ambiguities but we can try that first. Failing that, we could allow something like `ident` or `(ty)` (that is, if you want a more general type syntax you have to parenthesize it). That wouldn't be ideal but it'd be better than the status quo.

**Comment by Vurich** [comment]
Workaround: use `pub class JsBigArchive as BigArchive for ::BigArchive`. This macro only takes an `ident` instead of `ty` because it desugars to that.

**Comment by kjvalencik** [comment]
`declare_types` is deprecated.
