### ISSUE TITLE
Cannot create class for generic Rust type

### ISSUE THREAD

**Issue by phrohdoh** [neon-bindings/neon#168]
[`BigArchive`](https://github.com/Phrohdoh/libbig/blob/7f2328f066bb677b98f47fb5daf6912b2ede780a/src/lib.rs#L14) is `<T: Read + Seek>`

```rust
declare_types! {
    pub class JsBigArchive for BigArchive {
        init(call) {
            let scope = call.scope;
            let path = call.args.require(call.scope, 0)?.check::<JsString>()?.value();
            Ok(try!(BigArchive::new_from_path(&path)))
        }
    }
}

/*
error[E0243]: wrong number of type arguments: expected 1, found 0
  --> src/feature_neon/mod.rs:28:43
   |
28 |     pub class JsBigArchive for BigArchive {
   |                                           ^ expected 1 type argument

error[E0243]: wrong number of type arguments: expected 1, found 0
  --> src/feature_neon/mod.rs:28:43
   |
28 |     pub class JsBigArchive for BigArchive {
   |                                           ^ expected 1 type argument

error: aborting due to 2 previous errors

error: Could not compile `libbig`.
*/
```

```rust
declare_types! {
    pub class JsBigArchive for BigArchive<T> {
        init(call) {
            let scope = call.scope;
            let path = call.args.require(call.scope, 0)?.check::<JsString>()?.value();
            Ok(try!(BigArchive::new_from_path(&path)))
        }
    }
}

/*
error: no rules expected the token `<`
  --> src/feature_neon/mod.rs:28:42
   |
28 |     pub class JsBigArchive for BigArchive<T> {
   |                                          ^

error: Could not compile `libbig`.
*/
```

**Comment by dherman** [comment]
This one is a trickier issue: you're wanting to define a JS class for a generic type. Depending on what you're trying to do, you could just define the JS class for a specific instantiation of the type, e.g. `BigArchive<i32>` (and annoyingly, because of issue #167 you have to do a type alias like:

```rust
type BigArchiveOfInt = BigArchive<i32>;
declare_types! {
    pub class JsBigArchive for BigArchiveOfInt {
        ... 
    }
}
```

But I suspect that's going to be horrible as soon as you're looking for more than one instantiation of `BigArchive`. You _could_ define a macro to generalize this but it'll be painful.

The more general solution will be for us to find a way to define JS classes for generic types. One answer might be that you could define a generic class declaration like:

```rust
pub class JsBigArchive<T: Read + Seek> for BigArchive<T> { ... }
```

But you'd still have to instantiate `JsBigArchive` for each different type, which means you get a different JS class, with a separate constructor and prototype pair for each instantiation.

What this might want instead is to be able to define a single JS class for a generic Rust type, where the type argument has to implement coercion traits. So then you could write something like:

```rust
pub class<T: Read + Seek + ToRust + ToJs> JsBigArchive for BigArchive<T> { ... }
```

The macro would then automatically insert the appropriate coercions when going between Rust and JS.

But this is just a sketch of thoughts. We'll need to actually dive in and experiment. Your library could be a great test case! I'll look for you on Slack and see if we can define a minimal "hello world" use case that is representative enough to experiment with.

**Comment by Vurich** [comment]
Workaround: use `pub class JsBigArchive as BigArchive for BigArchive<i32>`. This macro only takes an `ident` instead of `ty` because it desugars to that.

**Comment by Vurich** [comment]
A possible solution to this (but not the issues with lifetimes) is to [recreate the syntax in the macro](https://play.rust-lang.org/?gist=2887353b8358cd66c1a8d1085177804f&version=stable). This doesn't work for lifetimes or traits that need parameters, though you can work around that with:

```rust
trait Concrete: Generic<Foo> {}
impl<T: Generic<Foo>> Concrete for T {}
```

This bumps the problem up to not being able to supply generic paramters to traits, which is slightly better than the existing situation.

**Comment by dbousamra** [comment]
> Alternative workaround: use `pub class JsBigArchive as BigArchive for BigArchive<i32>`. This macro only takes an `ident` instead of `ty` because it desugars to that.

This works well for me. Thank you

**Comment by kjvalencik** [comment]
`declare_types` is deprecated. `JsBox<T>` does not have this limitation.
