### ISSUE TITLE
Using declare_types with explicit lifetime

### ISSUE THREAD

**Issue by jugglingcats** [neon-bindings/neon#207]
I believe this is a direct consequence of https://github.com/rust-lang/rust/issues/34303 which hopefully will be fixed, but am adding here for awareness.

It doesn't seem possible to have a lifetime on the underlying struct for a Javascript class, eg:

```
pub struct TestMe<'a> {
    x: &'a mut i32
}

declare_types! {
    pub class JsTestMe for TestMe {
        init(call) {
            Ok(TestMe {x: &5})
        }
    }
}
```
This fails with compile error:
```
error[E0107]: wrong number of lifetime parameters: expected 1, found 0
  --> src\shm/mod.rs:99:35
   |
99 |     pub class JsTestMe for TestMe {
   |                                   ^ expected 1 lifetime parameter
```

**Comment by Vurich** [comment]
Workaround: use `pub class JsTestMe as TestMe for TestMe<'static>`. There is no way to do this with a generic parameter right now, but you can make it concrete.

**Comment by ryantate13** [comment]
Is it possible to get this to work with lifetimes other than `'static`? I get a `use of undeclared lifetime name` error when I try.

**Comment by kjvalencik** [comment]
@ryantate13 It is not because the lifetime _must_ be `'static`. The object is being handed over to v8 for tracking and garbage collection. Therefore, it must be bounded by the `'static` lifetime. I.e., the struct must be capable of being held for the entirety of the program.

If the struct were valid for a shorter time period, it might become invalid while it is still being held by Javascript. Dereferencing this struct would be a use-after-free bug.

Referencing counting (e.g., `Arc`) is a common way to upgrade something to a `'static` lifetime.

I'm going to close this issue because it sounds like `'static` is already supported and lifetimes other than `'static` cannot be supported.
