### ISSUE TITLE
neon build fails with node.js 10

### ISSUE THREAD

**Issue by hyperfekt** [neon-bindings/neon#305]
See nodejs/nan#766.

**Comment by mhsjlw** [comment]
I'm guessing that if https://github.com/neon-bindings/neon/blob/4e2273c14de6820d81cb377a44e5634b88f69174/crates/neon-runtime/package.json#L11 is bumped to `2.10.0` It'll work. I'll give it a try.

**Comment by mhsjlw** [comment]
Alright, it appears that 

https://github.com/neon-bindings/neon/blob/4e2273c14de6820d81cb377a44e5634b88f69174/crates/neon-runtime/src/neon.cc#L30-L32

this function fails to build due to 

```
../src/neon.cc:32:16: error: no member named 'Callee' in 'v8::FunctionCallbackInfo<v8::Value>'
  *out = info->Callee();
```

So it looks like it's been removed from V8? I'll keep investigating, but once this builds I'm guessing it will work.

**Comment by mhsjlw** [comment]
It does appear that it was marked as deprecated:

https://codereview.chromium.org/1582793004/patch/1/10001

But has since been removed:

https://chromium-review.googlesource.com/c/v8/v8/+/741600

I'll look at the possibility of moving to `->Data()`

**Comment by mhsjlw** [comment]
A PR has been opened with my changes
