### ISSUE TITLE
How to use JsArray

### ISSUE THREAD

**Issue by daihy8759** [neon-bindings/neon#336]
```javascript
addon.array_process([{
    'operator': 'print',
    'value': '232'
}, {
    'operator': 'print',
    'value': '23'
}])
```
```rust
    let js_arr: Handle<JsArray> = try!(try!(call.arguments.require(scope, 0)).check::<JsArray>());

    for i in 0..js_arr.len() {
        // 
    }
```
how can't i get values from array? any help?

**Comment by kjvalencik** [comment]
The trick is to include the `neon::js::Object` trait to provide the `get` method (`neon::object::Object` in upcoming `0.2`). You may also want to do a bounds check on each loop iteration since a JS getter could modify the object while iterating.

```
fn array_process(call: Call) -> JsResult<JsUndefined> {
	let scope = call.scope;
	let arr = call.arguments.require(scope, 0)?.check::<JsArray>()?;

	for i in 0..arr.len() {
		let item = arr.get(scope, i)?.check::<JsObject>()?;
		let operator = item.get(scope, "operator")?.check::<JsString>()?.value();
		let value = item.get(scope, "value")?.check::<JsString>()?.value();

		match operator.as_str() {
			"print" => {
				println!("{}", value);
			},
			_ => {
				let msg = format!("Unsupported operator: {}", operator);

				return JsError::throw(Kind::Error, &msg);
			}
		}
    }

	Ok(JsUndefined::new())
}
```

The below commit implements two methods of deserializing the array:
1. Writing pure neon code to read the objects from the array and then the keys from the objects.
2. Using `neon-serde` to deserialize into a `Vec` of enums (internally tagged with the `operator` key).

https://github.com/kjvalencik/neon-example/commit/72f2084741651fd897c5134aae753ec22f039872

**Comment by dai875939260** [comment]
thank you very much！it helped me a lot.

**Comment by amilajack** [comment]
I've documented this [here](https://amilajack.github.io/neon-docs/docs/en/js-array)
