### ISSUE TITLE
What is the plan for N-API compatibility?

### ISSUE THREAD

**Issue by ZhangHanDong** [neon-bindings/neon#338]
or Roadmap？

**Comment by Brooooooklyn** [comment]
Here is a minimal N-API library https://github.com/brooooooklyn/napi-rs which is still in developing.

**Comment by jbolila** [comment]
#202 has a similar question, and N-API is now on stable Node 10, and soon 8 (without the need of a flag), all well described in a recent blog post: 

https://medium.com/the-node-js-collection/n-api-next-generation-apis-for-node-js-native-addons-available-across-all-lts-release-lines-4f35b781f00e

Since this project has already a community of Rust + Node users, can't N-API be supported using the official https://github.com/nodejs/node-addon-api to generate the bindings and simplify the all process ?

**Comment by kjvalencik** [comment]
Thanks for the bump! N-API is part of the roadmap and could probably use an RFC outlining the plan. Here is my understanding of what's currently happening:

1. 0.2 removes features that don't have N-API counterparts.
2. Roadmap item to convert existing features to N-API
3. Distribution of pre-built modules relies on N-API

**Comment by ZhangHanDong** [comment]
@kjvalencik 

Thanks，I see. wait in hope.

**Comment by samvv** [comment]
I have created an issue in neon-bindings/rfcs#27.
