### ISSUE TITLE
trigger this event and callback at a suitable time

### ISSUE THREAD

**Issue by whaqzhzd** [neon-bindings/neon#369]
Is it possible to use js to listen for events sent by rust and trigger callbacks?
~~~js
var addon = require('../native');

var e = new addon.Event();

e.addEventlistener('event',(value)=>{
  console.log(value);
});
~~~

~~~rust

pub struct Event{
  cb
}

declare_types! {
  pub class jsEvent for Event{
    method addEventlistener(mut cx){
      ...
    }
  }
}
~~~

Trigger this event and callback at a suitable time

**Comment by kjvalencik** [comment]
I have bad news, interesting news and good news.

The bad news is this is not directly possible with the current API. There is no way for a rust thread to grab a VM lock. The only way to lock the VM is to initiate it from JS.

The interesting news is that there is an RFC and an implementation for this feature (aka, Worker Task)!
https://github.com/neon-bindings/rfcs/pull/15
https://github.com/neon-bindings/neon/pull/303

The good news is that you can fake this using channels, providing an async polling interface and a little bit of glue code in JS. I added a quick example to my kitchen sink project. The general idea:

* Create an enum to map events to their data
* Create a `JsClass` to hold the event receiver and a shutdown sender. The receiver needs to be reference counted and wrapped for internal mutability since it will be read from another thread. `Arc<Mutex<mpsc::Receiver<Event>>>`. A mutex is fine since we only expect `poll` to be called in our loop and we always need a mutable reference anyway (i.e., no lock contention).
* Start a background thread anyway that makes sense. It should accept a shutdown channel and return a channel that sends our event enums
* Create an async `Task` for polling the channel. Keep in mind that since we are polling in a loop, this will pretty much permanently take up one of the libuv threads. You may want to adjust `UV_THREADPOOL_SIZE` accordingly.
* Add methods to your `JsClass` for polling and shutting down. A shutdown isn't explicitly necessary since garbage collection will destroy your `JsClass` and this will close the shutdown channel which can be interpreted as a shutdown command. However, this is helpful since you will likely need it anyway and it better controls when the shutdown occurs.
* Some glue code in JS. Extend the `EventEmitter` class. Your constructor can create an instance of your `JsClass` and poll in a loop, receiving the events and emitting them.

https://github.com/kjvalencik/neon-example/commit/2ef932d42e2ce6dc7b5e11a013347de360dd134d

**Comment by whaqzhzd** [comment]
Thank you for your excellent answer, very helpful to me.
