### ISSUE TITLE
neon build should rebuild if nodejs version is changed

### ISSUE THREAD

**Issue by kdy1** [neon-bindings/neon#384]
See https://travis-ci.com/swc-project/node-swc/jobs/169705074

**Comment by amilajack** [comment]
Good catch. I'll start working on a fix for this

**Comment by dherman** [comment]
Great catch! I just talked with @amilajack about how to tackle this one. Here are the steps I think should work:

- [ ] BuildSettings.current() should detect the Node version (via `child_process.spawnSync("rustc", ["--version"])`
- [ ] add a `private node: string | null` property to BuildSettings class
- [ ] BuildSettings.construct() should take the Node version as an extra (`string | null`) parameter
- [ ] BuildSettings.fromJSON() and BuildSettings.toJSON() should also serialize/deserialize the Node version
- [ ] BuildSettings.match() should also compare the `.node` fields of the two instances

This could definitely use some tests, too. The caching logic has been brittle. If that turns out to be too hard, still best to implement this fix first and we can add tests separately, but see what you think you can do!
