### ISSUE TITLE
No way to build without --release?

### ISSUE THREAD

**Issue by anurbol** [neon-bindings/neon#463]
Hi guys :wave: Is it me or it's only possible to `neon build --release`?
If I run just `neon build` then I get this message `Neon only build with --release...`. What is the reason of that?

There are some conditional attributes in my code that depend on `debug_assertions`, so those don't work because of this. 

Response would be greatly appreciated, especially if soon.

**Comment by anurbol** [comment]
Is this behavior just for Windows? https://github.com/neon-bindings/neon/blob/845425b5aa63d5fbaaebd60d102b2250d06c1e3c/src/lib.rs#L341 

Why is that, do anyone know? :cry:

**Comment by kjvalencik** [comment]
This is a limitation of the windows build process. If you build on other OS, debug builds work as expected.

If you need windows support, a workaround is to add the following to your `Cargo.toml` to enable debug assertions on release builds.

```toml
[profile.release]
debug-assertions = true
```

**Comment by anurbol** [comment]
@kjvalencik Thanks so much for quick response. Does it have something to do with node-gyp and msvc? If yes, then I understand.

**Comment by kjvalencik** [comment]
To be honest, I'm not sure. It's been there a long time and I've never questioned it since I'm not a Windows user.

**Comment by anurbol** [comment]
Would be great. I am a newbie in Rust, but I'll probably try to test what happens if I remove that compile error line, and will write here.

**Comment by anurbol** [comment]
Uhm.. It seems it compiles. I'll recheck..

**Comment by anurbol** [comment]
@kjvalencik Everything works on windows. I removed the line from ~.cargo/registry/.../neon-0.3.3  
and everything builds just fine; also JS has not troubles requiring the built module. Made a pull request to comment those lines in the repo.

**Comment by anurbol** [comment]
Turns out there is some problem with building without the `--release` flag: `Error: internal error in Neon module: attempt to subtract with overflow`.

**Comment by kjvalencik** [comment]
Interesting. That seems like it's catching an actual bug. Are there any more details when run with `RUST_BACKTRACE=1`?

**Comment by anurbol** [comment]
@kjvalencik I am not sure I did it correctly: I ran 
`$Env:RUST_BACKTRACE=1; neon build` and then ran the js app that requires the addon. Still the same error `Error: internal error in Neon module: attempt to subtract with overflow` with no backtrace. What am I doing wrong?

**Comment by usagi** [comment]
I have the same interest for the issue. Have you @anurbol , @kjvalencik any additional infos?

---

I think, the issue is not a critical than before because developers who includes Windows target can use WSL2 environment in very easily. And we can split a NEON marshlling workspace and backend core business logics workspace then we avoid the problem very easy too. But, the situation is not beautiful adn confusible for newbiews then I want to solve it if possible.  🤔

**Comment by kjvalencik** [comment]
@usagi Most likely it's being suppressed by the overridden panic hook. You can try enabling the `default-panic-hook` feature flag in neon.

**Comment by usagi** [comment]
This post is a progress logging about my first trial of debug build in Windows. It's works at least the first "hello". 👍 

1. Modify the local clone of the `neon` repos for this experiment ( `C:\Users\usagi\tmp\z\WINDOWS_SPECIALIZED\neon` )
    1. Remove the safety code specialized for Windows from `src/lib.rs`

```rust
#[cfg(all(windows, not(neon_profile = "release")))]
compile_error!("Neon only builds with --release. For tests, try `cargo test --release`.");
```

2. Create a new neon app for this experiment ( `C:\Users\usagi\tmp\z\WINDOWS_SPECIALIZED\aaa` )
    1. `neon new aaa`
    2. Modify the dependencies to the path of (1) in the `native/Cargo.toml`
        1. `neon = { path = "../../neon" }` in the [dependencies]
        2. `neon-build = { path = "../../neon/crates/neon-build" }` in the `[build-dependencies]`
3. Build the app with debug
    1. `Neon build`
        - ; It could not be completed, but works until before the last linking of the `aaa.dll`.
        - ; And then, it displays the command logging of the linking stage with an errors.
    2. Copy and paste the linking command line to a text editor in temporaly because it is sooooooo long 🍝
        - ; `link.exe (brabrabra...)` is it.
    3. Modify the command line manually; Because it looks like a simple common trouble about a msvc toolchain's MT or MTd runtimes mainly and I think I can fix quickly with hand writing in temporaly.
        1. Add: `"msvcrtd.lib"`
        2. Add: `"/NODEFAULTLIB:libcmtd.lib"`
        3. Remove: `"msvcrt.lib"`
        4. Remove: `"/DEF:C:\\Users\\(your-user-name)\\AppData\\Local\\Temp\\rustcsVVlTF\\lib.def"`
    4. Run the modified linking command line use the `x64 Native Tools Command Prompt for VS 2019`
        - ; You don't worry about relative paths because the command line made with absolute paths.
        - ; If you could not paste all of the command line then you may remove a part of paths of .lib arguments because it included of `/LIBPATH:` argument, maybe.
        - ; It will be create the `aaa.dll` file in the `native/target/x86_64-pc-windows-msvc/debug/deps` directory.
    5. Copy or rename the extension from `aaa.dll` to `aaa.node`
    6. Test the `aaa.node` with Node.js
        - ; eg. in command line: `node -e "console.log(require('./native/target/x86_64-pc-windows-msvc/debug/deps/aaa.node').hello())"` in the project root directory of aaa project.
        - ; eg. in Node.js interactive shell:

```node
PS C:\Users\usagi\tmp\z\WINDOWS_SPECIALIZED\aaa\native> node
Welcome to Node.js v13.5.0.
Type ".help" for more information.
> const aaa = require('./target/x86_64-pc-windows-msvc/debug/deps/aaa.node')
undefined
> aaa.hello()
'hello node'
>
```

eg. with VSCode + LLDB debugger IDE

`launch.json`:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "lldb",
      "request": "launch",
      "name": "Debug: Backend",
      "program": "node",
      "args": [
        "-e",
        "console.log(require('./native/target/x86_64-pc-windows-msvc/debug/deps/aaa.node').hello())"
      ],
      "cwd": "${workspaceFolder}"
    }
  ]
}
```

And then:

![image](https://user-images.githubusercontent.com/115972/77506801-1ab84100-6eaa-11ea-82ca-9831b1680a30.png)

The debugger works fine, at least in the super simple "hello". 👍 

Maybe, this problem of the linking stage is not the core of the problem. The main reason of the feature disabling by  is in a more internal somewhere. But, if the problem is only it then It may solve easy. I guessing, it be solve if fix the usage about `node-gyp`, or at least write a specialized linking process to a ".cargo/config" for Windows in temporarily.

---

Related commit logs:

- https://github.com/neon-bindings/neon/commit/ea51376
- https://github.com/neon-bindings/neon/commit/2b28a28

Hmm, the main reason is not written in these commit logging, but it may mean the reason is a very simple. 💡

**Comment by usagi** [comment]
And then, I found minimum workaround or fixing for the linker trouble.

Add the below code to the `pub fn setup` for Windows version in the `neon/crates/neon-build/src/lib.rs` file:

```
            if debug
            {
                println!("cargo:rustc-link-lib=msvcrtd");
            }
```

Then, `neon build` (and of course `cargo build` in the `native` directory too) will be works expectedly, and `cli` (=`neon` command) create `native/artifacts.json` and `index.node` files. 👍 

### Summary of "How to build a debug version `native/index.node` in Windows experimentally" is:

1. Modify the NEON codes:
    1. Remove/Comment the safety codes from the `neon/src/lib.rs` in temporaly; The details is in the previous my post.
    2. Add the `msvcrtd` fixing; The detail is in above of in this post.
2. Modify the app codes:
    1. `native/Cargo.toml`:
        1. `[dependencies]`: `neon = ` to `{ path=(your-modified-neon-path) }`
        2. `[devDependencies]`: `neon-build = ` to `{ path=(your-modified-neon-path)/crates/neon-build }`
3. Then, you can build a debug version use `neon build`.

But, it is not the solution for this issue **yet**. The debug version binary built using this method is not tested enough. I'll test with a native code debugger for more codes based on the examples. And, if it has not a critical problems then I'll create a PR.

**Comment by usagi** [comment]
@anurbol Could you share your happened code about  https://github.com/neon-bindings/neon/issues/463#issuecomment-558215599 ? Of course don't worry, any infos are so helpful for me now anything either a simple hello-world or a more complexed something.

**Comment by usagi** [comment]
I'd completed a testing for all of the examples exclude 17(electron app), 18(publishing modules),21(Bindgen) that reconfigured to use the modified neon. No errors caused from the debug build mode with my modified neon. And, it could be native code debugging with msvc-debugger and lldb. Of course, the setting of these examples and the neon was modified to use with `default-features = false` and `features = [ "default-panic-hook", "legacy-runtime" ]` just in case.

Thus, I'll PR it soon. 🎉

**Comment by usagi** [comment]
#### Summary at now

1. This problem not happens when user using:
    - Node.js-8.17.0 ( 2020-03-27 by @usagi )
    - Node.js-9.11.2 ( 2020-03-27 by @usagi )
2. This problem happens when user using:
    - Node.js-10.18.1 ( 2020-03-27 by @usagi )
    - Node.js-11.10.1 ( 2019-04-23 by @nemoNoboru )
    - Node.js-11.10.1 ( 2019-04-22 by @moriyalb )
    - Node.js-13.5.0 ( 2020-03-21 by @usagi )

And, 

1. Maybe, this problem happens from...:
    - STDOUT ( `console.log` ) when using at the same process...:
        - with `fs` and `require('rsvp').denodeify` ( because it not happens if comment these `await` lines in `cli/src/ops/neon_new.ts` )
        - with STDIN ( because it happens only `neon new` )
2. This problem be solve if use a newer version `fs.promises` ( PR #506 )
    - but it is not available in Node.js < 10.
        - NEON supports Node.js-{8, 10, 12} officially

And, 

1. This problem is not critical for `neon new`...
    - because this problem happens after compled of main work ( the remain works is only show the flavor text )
        - It is no problems if use `CTRL+C` ( the workaround )

---

🤔  Hmm, I have a little motivation to this issue only the latest environment supports. But I have no interest for older environments and then I don't know the best method that supports the latest and an older versions widely in Node.js. Especially, Node.js and `fs` looks like jumped between the version 8 and 10, hmm.... I don't know how solve it in practical with no over costs. Maybe, if use sync version APIs... but... hmm... 😭
