### ISSUE TITLE
capnp help

### ISSUE THREAD

**Issue by Tonyce** [neon-bindings/neon#497]
I have the questions: if I write cap'n proto with capnp-rust that neon wrap , will I get the node-capnp problem?

[_The node-capnp problem:_ ](https://github.com/capnproto/node-capnp#caveats)
> Because v8 cannot inline or otherwise optimize calls into C++ code, and because the C++ bindings are implemented in terms of the "dynamic" API, this implementation is actually very slow. In fact, the main advantage of Cap'n Proto -- the ability to use the wire format as an in-memory format -- does not apply here, because accessor overhead of such an approach would be too high.

**Comment by kjvalencik** [comment]
Yes, it would most likely have the same caveats. FFI is not a good fit for small, fast operations. Ideally large amount of work is completed in C++/Rust before returning to V8 in order to overcome the overhead of the call.

For example, a pattern that is efficient if it works in your use case, is passing `Buffer` objects that represent serialized Cap'n Proto to Neon, performing some operations and responding with either another serialized `Buffer` object or with a small response.
