### ISSUE TITLE
Is there a way to not need visual c++ in production?

### ISSUE THREAD

**Issue by killpowa** [neon-bindings/neon#519]
Right now my app is failing to run with an error in the main thread
![immagine](https://user-images.githubusercontent.com/10165264/82162850-c7f67680-98a7-11ea-8f09-ece22c8ee55c.png)

Installing Visual C++ solves the issue but I don't want my users to necessarily have it...
Am I building it in the wrong way / is there something I can do to fix this?

**Comment by retep998** [comment]
Rust has a `crt-static` target feature specifically to statically link the CRT so users don't need to install the VC++ redistributable. Because this crate links in some C code, neon will need to update the build script to read the CARGO_CFG_TARGET_FEATURE environment variable and check if it contains `crt-static` to determine which RuntimeLibrary to use. 0 if it does, and 2 if it does not.

**Comment by killpowa** [comment]
Oh ok, so you need to update something in neon to do that? Just as reference, this is my neon package: https://github.com/gorilla-devs/murmur2-calculator which is used and compiled here https://github.com/gorilla-devs/GDLauncher/blob/master/scripts/buildNativeDeps.js

**Comment by kjvalencik** [comment]
This only impacts the legacy backend. The Node-API backend only uses cargo and can be statically linked or use gnu.
