### ISSUE TITLE
Modules that use neon should specify the rust-lang under engines

### ISSUE THREAD

**Issue by vladikoff** [neon-bindings/neon#56]
I was just installing something and had rust version 1.5, the module failed to install.
I updated to rust 1.7 and everything went okay.

We should investigate if it is possible for neon-cli (or something else) to warn the user that the module built with neon was tested with some rust version 1.x

Ref: https://docs.npmjs.com/files/package.json#engines

Sorry if this is the wrong place to file this.

**Comment by dherman** [comment]
I think helping people debug problems relating to the version of Rust they're using is a valid issue, but I think if we did something like this it would belong at the cargo level, not the `package.json` level. I also want to be careful about this one because the cargo team has been pretty conservative about adding such a feature due to unintended ecosystem effects.

I'm going to close this for now, because I think it requires an RFC to think through the design. But if someone would like to investigate this I would definitely encourage an RFC!

**Comment by vladikoff** [comment]
Okay thanks Dave!
