### ISSUE TITLE
JsBox

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#561]
This is a placeholder issue for now until we have an RFC.

We should consider a simpler primitive than classes for sharing Rust data structures with JavaScript and back again. A couple years ago, @matklad proposed the idea of a `JsBox` primitive, which would be a basic building block for sharing Rust data with JS, around which you could define custom JS classes _mostly in pure JavaScript_.

Another interesting development: infinyon/node-bindgen has done some great innovation on auto-generating JavaScript classes with a procedural macro, as opposed to the old-style `macro_rules` macro of our class system. I think that's a better direction in the long-term, but it could potentially build on `JsBox` as an underlying primitive.

And in the medium-term, I think we could use `JsBox` to experiment with pushing the `class` macro out into a third-party library and get it out of Neon proper. That would clear a path to prevent us from getting stuck permanently with a 1.0 release on a macro that was clearly never fully baked.

**Comment by dherman** [comment]
Here is @matklad’s [comment about the `JsBox` idea from 2017](https://github.com/neon-bindings/rfcs/issues/6#issuecomment-353403121).

**Comment by kjvalencik** [comment]
@dherman Interestingly the pattern that explained in that comment (simple classes that are only used for wrapping and get passed as the first argument to functions) is _exactly_ the pattern I fell into. This pattern is also beneficial for factory classes instead of initializing data with an `Option`.

**Comment by kjvalencik** [comment]
Notes from investigation:

* [`std::any::Any`](https://doc.rust-lang.org/std/any/trait.Any.html) does most of the hard work of type tagging and downcasting.
* [`std::any::type_name`](https://doc.rust-lang.org/std/any/fn.type_name.html) allows generating nice informative `TypeError`. E.g., `TypeError: Failed to downcast to "my_crate::MyStruct"`
* [`napi_create_external`](https://nodejs.org/api/n-api.html#n_api_napi_create_external) provides the required functionality. However, it does not [currenty](https://github.com/nodejs/node/issues/28164) support external tags. Undefined behavior would result if the user passes in an external from another library.
* Needs to be double boxed since N-API will only has space for a thin pointer
* Should this use the existing `borrow` API or should we tie it to `Context` borrows?
* This combined with the upcoming `Persistent` RFC are capable of replacing both the `Task` and `EventHandler` APIs.

**Comment by goto-bus-stop** [comment]
For reference, the RFC is here: https://github.com/neon-bindings/rfcs/pull/33
