### ISSUE TITLE
neon-create-app

### ISSUE THREAD

**Issue by dherman** [neon-bindings/neon#566]
Implement the `neon-create-app` CLI.

**Comment by ArturAralin** [comment]
@dherman it's interesting for me. Can you got me more details about requirements?

**Comment by dherman** [comment]
@ArturAralin You’re too fast for me! 😂 I’ve just written a [draft RFC](https://github.com/neon-bindings.com/rfcs/pulls/36). I haven’t reviewed your code closely yet, but what you’ve done is probably a good first step for refactoring the existing neon-cli code into a separate tool!

The next steps would be to pull shared functionality into a helper library and use that from each of three separate front ends (-app, -lib, -electron-app). @amilajack has suggested that we move all of these into the Neon repo using monorepo tooling like Lerna, since they’re all being tightly co-developed, which seems like a good idea.

**Comment by ArturAralin** [comment]
@dherman let me know when RFC will be finished 😄

**Comment by kjvalencik** [comment]
@ArturAralin We're excited to have you helping! We're still bike shedding the directory structure for `create-neon-app`, but we've come to consensus on `create-neon-lib`. Are you interested in working on that?

If so, I can provide some more context. Firstly, the intent of these new libs are to _only_ support the N-API backend. The good news is that we've managed to eliminate the need for the `neon` CLI tool when building. Instead, a user can directly `cargo build`.

Along with the simpler build process, we observed that projects in the wild tend to make a neon library Rust only and put JavaScript code elsewhere. To better match that pattern, we would like a flattened directory structure. Instead of a `neon` project being a Node project with a Rust directory (`/native`) inside it, it's a _Rust_ project with just enough glue (a `package.json`) to require it from a node project.

I've built a proof of concept and you can see this directory structure on my branch: https://github.com/neon-bindings/neon/tree/kv/no-cli-build/test/napi

Let me know if you have any questions!

**Comment by ArturAralin** [comment]
@kjvalencik does my draft satisfy as base of CLI tool or you have any special requirements or notes?

https://github.com/ArturAralin/create-neon-app

**Comment by kjvalencik** [comment]
@ArturAralin We aren't ready for `create-neon-app`, there's still some debate on the proper structure. `neon-create-lib` should be a flattened structure similar to my test branch https://github.com/neon-bindings/neon/tree/kv/no-cli-build/test/napi.

**Comment by dherman** [comment]
Update: we're simplifying the Neon project creation down to a single CLI workflow. See: https://github.com/neon-bindings/neon/issues/565#issuecomment-780729310
