### ISSUE TITLE
Feature request: don't set the panic hook under RUST_BACKTRACE=1

### ISSUE THREAD

**Issue by jrose-signal** [neon-bindings/neon#629]
Neon sets Rust's panic hook to avoid printing backtraces for panics that will be turned into JavaScript errors, which is sensible. However, this also makes it hard to *debug* panics, especially those that get swallowed at some higher level. There's already a feature to avoid setting the hook, `default-panic-hook`, but that requires a rebuild to see the results. It would be nice™ if an environment variable could be used to the same effect, and using Rust's typical `RUST_BACKTRACE=1` would make a lot of sense.

**Comment by kjvalencik** [comment]
Additionally, the `default-panic-hook` is confusing because it gets emitted by a macro into the _user's_ code. It means the feature needs to be in the dependent crate, not Neon.

I like using the `RUST_BACKTRACE` style environment variable, but would likely opt for a different variable. Maybe `NEON_BACKTRACE`.

As a workaround, this can be implemented in your module by using the `default-panic-hook` feature and writing a panic hook that uses the flag.

**Comment by kjvalencik** [comment]
The panic hook is not set for `#[neon::main]` which is now default.
