### ISSUE TITLE
Documentation for N-API and examples?

### ISSUE THREAD

**Issue by jessbowers** [neon-bindings/neon#683]
It seems from feedback I've read that the future is the N-API and not the macros in the readme & examples. Are there docs or examples on how to use those apis yet? I've looked in a number of places and I'm coming up short. If not, are there examples in the wild? I'd really like to be on the future path if possible.

**Comment by kjvalencik** [comment]
The best docs at the moment are the tests https://github.com/neon-bindings/neon/tree/main/test/napi.

The API docs are available on docs.rs: https://docs.rs/neon/0.7.1-napi/neon/index.html

If you don't mind, I'm closing this issue since we have a few open issues for better docs: https://github.com/neon-bindings/neon/issues/560
