### ISSUE TITLE
Passing number arrays from Rust to JS

### ISSUE THREAD

**Issue by evilfer** [neon-bindings/neon#743]
I'm trying to pass an array from Rust to JS using Neon. So far I'm using this code:

```rust
  let mut buffer = {
      let mut buffer = JsBuffer::new(&mut cx, (mem::size_of::<f64>() * data.len()) as u32)?; // this is the slowest bit in the Rust code execution.

      let guard = cx.lock();
      let mut slice = buffer.borrow_mut(&guard).as_mut_slice::<f64>();
      for (i, v) in data.iter().enumerate() {
          slice[i] = *v;
      }
      buffer
  };

  Ok(buffer.upcast())
```

This works, but I think it's not very efficient (e.g., it's noticeable slower than the equivalent transfer between wasm and js for the same initial `Box<[f64]>`). 

I wanted to ask, is there a more efficient way of creating the JsBuffer, perhaps by moving the data out of the original `Box<[f64]>`? (I could work with `[u8]` too).

**Comment by kjvalencik** [comment]
There are a couple different options. While still copying the data, like in your example, there will be better performance using [`std::slice::copy_from_slice`](https://doc.rust-lang.org/std/primitive.slice.html#method.copy_from_slice) instead of individually copying elements.

Alternatively, both `JsBuffer` and `JsArrayBuffer` support moving an entire `Vec<u8>` (technically, anything that's `DerefMut<u8>`) without copying by using [`JsArrayBuffer::external`](https://docs.rs/neon/0.8.2-napi/neon/prelude/struct.JsArrayBuffer.html#method.external).
