### ISSUE TITLE
Process never exits when an object with a Channel is used with a timeout

### ISSUE THREAD

**Issue by Thoralf-M** [neon-bindings/neon#776]
Process never exits when an object with a Channel is used with a timeout >~10 seconds
```JS
setTimeout(() => {
    console.log('Finished:', new WithChannel('Test').name())
    // }, 100); // small timeout, process will exit
}, 10000);// timeout around 10 seconds or higher, process will never exit
```
```Rust
pub struct WithChannel {
    channel: Channel,
    name: String,
}

impl Finalize for WithChannel {}

impl WithChannel {
    fn new(channel: Channel, name: String) -> Arc<Self> {
        Arc::new(Self { channel, name })
    }
}

pub fn with_channel_new(mut cx: FunctionContext) -> JsResult<JsBox<Arc<WithChannel>>> {
    let name = cx.argument::<JsString>(0)?;
    let name = name.value(&mut cx);
    let channel = cx.channel();
    let wrapper = WithChannel::new(channel, name);

    Ok(cx.boxed(wrapper))
}

pub fn with_channel_name(mut cx: FunctionContext) -> JsResult<JsString> {
    let wrapper = Arc::clone(
        &&cx.this()
            .downcast_or_throw::<JsBox<Arc<WithChannel>>, FunctionContext>(&mut cx)?,
    );
    let name = wrapper.name.clone();

    Ok(cx.string(&name))
}
```
The channel isn't even used, but the process keeps running for some reason

A full example is here https://github.com/Thoralf-M/neon-process-hangs

**Comment by kjvalencik** [comment]
This seems to be working as expected. Channels keep the process alive (unless unreferenced) and this is inside an object that hasn't been garbage collected. The long timeout is likely moving it into perm space. It should eventually exit after a full gc.

Try forcing a garbage collection after the object goes out of scope to verify.

**Comment by kjvalencik** [comment]
This test (https://github.com/neon-bindings/neon/blob/1d89872de37e3cd6da79b3999bfbb22c1cf3c4fd/test/napi/lib/threads.js#L51), demonstrates a Channel inside a wrapper object that eventually drops after a GC. All the tests in here force a GC after the test instead of needing to wait.

**Comment by Thoralf-M** [comment]
Thanks for the response, but I still can't get it working
```JS
(async function () {
    setTimeout(() => {
        console.log('Finished:', new WithChannel('Test').name())
    }, 10000); // timeout around 10 seconds or higher, process will never exit
})();
global.gc();
```
running with `node --expose-gc index.js`

**Comment by kjvalencik** [comment]
In this example, the `gc` is executing before the `WithChannel` instance is created.

Can you try putting the GC in a timeout that's longer than  the inner timeout and see if that has an effect?

```js
setTimeout(global.gc, 12000);
```

Sorry that I'm not able to test myself. I won't have access to a computer until next week.

**Comment by Thoralf-M** [comment]
Ok this works, but doesn't really help because we can't expect from our users to do it like that

Is there no other way to handle it than forcing a garbage collection?

**Comment by kjvalencik** [comment]
It should _eventually_ garbage collect on its own. If you need tighter control over this, there are a couple of options.

Expose a `close` method that explicitly drops the inner data. It would need to be in an `Option` and throw errors if `None` (already closed).

Another option is to `unref` (https://docs.rs/neon/0.9.0/neon/event/struct.Channel.html#method.unref) the channel. Unreferenced channels don't keep the event loop alive when empty. If you don't need to keep the event loop running, it could be the default or you could expose an `unref` method (this is what timers in Node.js do, https://nodejs.org/api/timers.html#timers_timeout_unref).

You could also kind of split the difference by making the `close` method `unref` instead of completely dropping the channel.

Unfortunately, there's no way to force the garbage collector to free a particular object.
