### ISSUE TITLE
Closure support on JsFunction::new

### ISSUE THREAD

**Issue by HADMARINE** [neon-bindings/neon#809]
Is there any method to bind closure function to JsFunction?

**Comment by kjvalencik** [comment]
Neon does not currently provide a way to create a `JsFunction` from a closure. This was intentionally omitted because Node-API did not provide a hook to safely drop the data when it was garbage collected, resulting in a leak. However, `napi_add_finalizer` was added in Node-API 5. There are some ergonomics issues that would be blocked by GATs, but it mostly just needs implementation.

With that said, I think your problem could be solved with `JsBox`. The docs include an example of this pattern. A JavaScript class can be created with some glue code in JavaScript.

https://docs.rs/neon/0.9.1/neon/types/struct.JsBox.html

**Comment by kjvalencik** [comment]
This was implemented.
