### ISSUE TITLE
vec_to_array() docs example not compiling

### ISSUE THREAD

**Issue by binajmen** [neon-bindings/neon#820]
Hi,

I want to convert a `Vec` to `JsArray` following the docs ([here](https://neon-bindings.com/docs/arrays#converting-a-rust-vector-to-an-array)):
```rust
use neon::prelude::*;

fn vec_to_array<'a, C: Context<'a>>(vec: &Vec<String>, cx: &mut C) -> JsResult<'a, JsArray> {
    let a = JsArray::new(cx, vec.len()); // <-- issue 1
                             ^^^^^^^^^ expected `u32`, found `usize`
    for (i, s) in vec.iter().enumerate() {
        let v = cx.string(s);
        a.set(&mut cx, i as u32, v)?; // <-- issue 2
          ^^^ the trait `neon::context::Context<'_>` is not implemented for `&mut C`
    }

    Ok(a)
}
```
The first issue is trivial: you have the choice to cast `as u32` or to `try_into().unwrap()`.

The second issue is not trivial, at least for me.. Could someone explain me the issue and how to solve it?

Thank you!

**Comment by kjvalencik** [comment]
Sorry about the inconsistencies! We recently switched the default backend to use Node-API and that included a number of breaking changes. Fixing all the docs is an active work in progress!

The second example is limitation of auto-deref and trait inference in Rust. In other words, since `cx` is already `&mut C`, `a.set` is receiving `&mut &mut C` instead of `&mut C`. Remove the `&mut` and it should be fixed.

```rust
a.set(&mut cx, i as u32, v)?;
```

**Comment by binajmen** [comment]
Thank you!
