### ISSUE TITLE
Can't build on Alpine: target `aarch64-unknown-linux-musl` does not support these crate types

### ISSUE THREAD

**Issue by gitmalong** [neon-bindings/neon#823]
Dockerfile
```
FROM rust:alpine3.14 as builder
WORKDIR /usr/src/myapp
COPY src_rust/ .
RUN npm run build-release --prefix my-app-rust-bindings
```

Error
```
error: cannot produce cdylib for `my-app-rust-bindings v0.1.0 (/usr/src/myapp/my-app-rust-bindings)` as the target `aarch64-unknown-linux-musl` does not support these crate types
Did not copy "cdylib:my-app-rust-bindings"
```

While the local build on my machine works with `npm run build-release --prefix my-app-rust-bindings`

**Comment by kjvalencik** [comment]
Building `cdylib` with Rust is not fully supported. See https://github.com/rust-lang/rust/issues/59302 for more details.

There is _some_ support by using the [`crt-static`](https://rust-lang.github.io/rfcs/1721-crt-static.html) feature to switch to dynamic linking the C runtime (default is static). This can be set either with the environment variable `RUSTFLAGS="-C target-feature=-crt-static"` or with a `.cargo/config.toml`.

```toml
[build]
rustflags = ["-C", "target-feature=-crt-static"]
```

After adding that flag, I am able to successfully build and execute a simple Neon module. However, since this is not a fully implemented feature, you may run into other issues. For dockerizing Neon apps, I highly recommend using [`debian:stable-slim`](https://hub.docker.com/_/debian) docker container. It's _nearly_ as small `alpine`, but since it's `glibc` based instead of `musl`, it won't have as many issues building native code.

Thanks for your interest. I'm going to close this issue since it is a limitation of Rust and outside the scope of Neon.

**Comment by rtritto** [comment]
@kjvalencik currently what's the best distro to use with Docker and build all [tier 1 platforms](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-1-with-host-tools)?

**Comment by kjvalencik** [comment]
I believe alpine works these days with cdylib targets.
