### ISSUE TITLE
<FunctionContext>#number supports u32 not u64?

### ISSUE THREAD

**Issue by kakarot-dev** [neon-bindings/neon#831]
Does `<FunctionContext>#number` support u64?
if not, is it for a reason?

**Comment by kjvalencik** [comment]
It does not. It only supports types than can be safely converted to an `f64`. This is because the JavaScript Number type is a 64-bit float. It's not possible to losslessly represent an integer larger than 53-bit.

If you know that the value will always be smaller, the `as` keyword can be used to cast bytes, otherwise `.try_into()` attempts a conversion and returns an error.

```rust
fn example(mut cx: FunctionContext) -> JsResult<JsNumber> {
    let n = 42usize.

    n.try_into::<f64>()
        .map(|n| cx.number(n))
        .or_else(|err| cx.throw(err.to_string()))
}
```
