### ISSUE TITLE
Is there any best practice about converting javascript object to rust data?

### ISSUE THREAD

**Issue by dickeylth** [neon-bindings/neon#886]
I read the doc and there's [Converting Rust data to JavaScript](https://neon-bindings.com/docs/objects/#converting-rust-data-to-javascript) part, in my case I want to convert a `JSObject` param to rust struct data and I did not find the right solution. I see there's a relevant issue https://github.com/neon-bindings/neon/issues/524 discussing about this and it seems it's suggesting using `neon_serde` package, however the package `neon_serde` seems not update for a long time, so my questions:

1. Is using `neon-serde` still is the suggested way to process jsobject to rust struct? Is `neon-serde` still actively maintained?
2. for javascript objects which have values that are objects which have innumerable keys, for example pass a url seachParams, what's the suggested struct definition?

**Comment by kjvalencik** [comment]
1. [`neon-serde2`](https://crates.io/crates/neon-serde2) is a maintained fork.
2. Probably a `HashMap<String, String>`, but see the [`serde` docs](https://docs.serde.rs/serde/index.html) for more information.

You may also want to considering serializing complex data structures to JSON instead. It can often perform better than directly transcoding from JavaScript to Rust because of the overhead of Node-API calls.
