### ISSUE TITLE
Optional argument

### ISSUE THREAD

**Issue by cisaacson** [neon-bindings/neon#927]
We have a use case where an optional `boolean` type is passed to a function. The code we are using is:

```
    ...
    let pad_with_max_arg = cx.argument_opt(2);
   ...
    let pad_with_max = match pad_with_max_arg {
        Some(v) => {
            dbg!("pad_with_max: {:?}", v);
            let js_boolean = v.downcast_or_throw::<JsBoolean, _>(&mut cx)?;
            Some(js_boolean.value(&mut cx))
        }
        None => None,
    };
```
The downcast fails, with this error: `TypeError: failed to downcast any to boolean`

We added a `dbg!` call, and its output shows:
```
v = Handle {
    value: 0x00007ff7bfef46d0,
    phantom: PhantomData,
}
```

How should we do this? We consider this an optional argument, so shouldn't the `Some` value be a `JsBoolean` or at least cast-albe to that? We need to use an `Option<bool>` to pass to another regular Rust `fn`. 

Please let us know how we should do this.

**Comment by kjvalencik** [comment]
This code is written correctly and will do what you want. It will *not* throw when no argument is passed in. However, it *will* throw if you pass in `undefined` or `null`.

For example, in this code:

```rust
fn maybe_boolean(mut cx: FunctionContext) -> JsResult<JsValue> {
    let value = cx
        .argument_opt(0)
        .map(|v| Ok(v.downcast_or_throw::<JsBoolean, _>(&mut cx)?.value(&mut cx)))
        .transpose()?;

    if let Some(value) = value {
        return Ok(cx.boolean(value).upcast());
    }

    Ok(cx.undefined().upcast())
}
```

* ✅ If you call `maybe_boolean()`
* ✅ If you call `maybe_boolean(true)`
* ✅ If you call `maybe_boolean(false)`
* ❌  If you call `maybe_boolean(undefined)`. This throws an exception.

If you don't care *what* type it is and are okay with `None` if it's anything except a boolean, you can use `downcast` instead of `downcast_or_throw`.

```rust
    let value = cx
        .argument_opt(0)
        .and_then(|v| v.downcast::<JsBoolean, _>(&mut cx).ok())
        .map(|v| v.value(&mut cx));
```

If you want to treat `null` and `undefined` special (like the argument isn't being passed), this gets a bit more complicated.

```rust
    let value = cx
        .argument_opt(0)
        .map(|v| {
            if let Ok(v) = v.downcast::<JsBoolean, _>(&mut cx) {
                Ok(Some(v.value(&mut cx)))
            } else if v.is_a::<JsUndefined, _>(&mut cx) || v.is_a::<JsNull, _>(&mut cx) {
                Ok(None)
            } else {
                cx.throw_type_error("pad_with_max must be a boolean")
            }
        })
        .transpose()?
        .flatten();
```

* ✅ If you call `maybe_boolean()`
* ✅ If you call `maybe_boolean(true)`
* ✅ If you call `maybe_boolean(false)`
* ✅ If you call `maybe_boolean(undefined)`
* ✅ If you call `maybe_boolean(null)`
* ❌  If you call `maybe_boolean(42)`. This throws an exception.

There have been discussions about providing a more ergonomic API for this pattern, but there isn't consensus over whether it should include `JsNull` or not.

As an aside, if you don't care for the chaining version, here's a version with just `match`:

```rust
    let value = match cx.argument_opt(0) {
        None => None,
        Some(v) => match v.downcast::<JsBoolean, _>(&mut cx) {
            Ok(v) => Some(v.value(&mut cx)),
            Err(_) if v.is_a::<JsUndefined, _>(&mut cx) => None,
            Err(_) if v.is_a::<JsNull, _>(&mut cx) => None,
            Err(_) => return cx.throw_type_error("pad_with_max must be a boolean"),
        },
    };
```

Does this answer your question?

**Comment by cisaacson** [comment]
@kjvalencik Thanks very much for the detailed explanation, it is very helpful. This does answer my question. It would be a great thing if there were more examples and documentation like this too. 

I'll close this issue.
