### ISSUE TITLE
How to grab a context from another thread?

### ISSUE THREAD

**Issue by victorteokw** [neon-bindings/neon#974]
Thanks for this great binding package! 👏

I have some rust code to save async callbacks into hashmaps. When some rust code is running, these callbacks are fetched and executed. However, I cannot get a context to execute JS code that passed in.

Is there any way to grab a context when there aren't contexts from the parameters?

**Comment by kjvalencik** [comment]
It's not possible to get a `Context` on another thread because it represents access to the single-threaded VM. However, you can use `Channel` to schedule a callback to be executed on the main thread.

Documentation on this is in the [events module](https://docs.rs/neon/latest/neon/event/index.html).

[This example](https://github.com/neon-bindings/examples/tree/main/examples/tokio-fetch) demonstrates using `Channel` along with the tokio runtime for async handling.
